#### Business Understanding
**Problem Statement:** Access to timely and reliable healthcare remains a major challenge, especially in regions with:
- Limited doctor-to-patient ratios 
- Long waiting times at clinics 
- High cost of consultations 
- Low health literacy among patients 
Many individuals:
- Ignore early symptoms 
- Misinterpret health information online 
- Delay seeking care until conditions worsen 
At the same time, general-purpose AI systems often:
- Provide unsafe or inaccurate medical advice 
- Lack grounding in trusted clinical guidelines 
- Do not assess urgency (triage) effectively 

This creates a critical gap: There is no widely accessible, safe, and intelligent system that can guide patients on what to do next based on their symptoms, without attempting full diagnosis or unsafe prescriptions.
Project Description:  Smart Doctor is a RAG-based AI Medical Triage & Advisory Assistant designed to:
- Interact with patients via text (and later voice) 
- Collect symptoms through structured conversation 
- Ask intelligent follow-up questions 
- Assess the urgency of the condition (triage) 
- Provide safe, evidence-based health advice 
- Recommend next steps (self-care, clinic visit, emergency care) 
- Store patient interaction data securely for future reference 

The system leverages:
- Large Language Models (LLMs) for conversation 
- Retrieval-Augmented Generation (RAG) for grounded medical knowledge 
- Rule-based logic for safe triage decision-making 

Importantly, the system:
Does NOT diagnose or prescribe medication, but instead supports decision-making and early intervention.
 Project Measurables (KPIs):
AI Performance Metrics

**1. Symptom Extraction Accuracy**
- Percentage of correctly identified symptoms from user input 
- Target: ≥ 85% accuracy 

**2. Triage Classification Accuracy**
- Agreement with medical guidelines or expert validation 
- Target: ≥ 90% for rule-based scenarios

**3. Response Grounding Score (RAG Quality)**
- Percentage of responses backed by retrieved medical sources 
- Target: ≥ 95% grounded responses 
 B. Safety Metrics

**4. Emergency Detection Recall**
- % of true emergencies correctly flagged 
- Target: ~100% (very critical) 

**5. Hallucination Rate**
- % of responses containing unsupported claims 
- Target: < 5% 

**6. Unsafe Recommendation Rate**

- Instances of: 
    - Prescriptions 
    - Confident diagnosis 
    - Target: 0% 
    
C. User Experience Metrics

**7. Conversation Completion Rate**
- Percentage of users who finish triage flow 
- Target: ≥ 80% 

**8. User Satisfaction Score**
- Feedback rating (1–5 scale) 
- Target: ≥ 4.0 

 D. System Metrics

**9. Response Time**
- Time taken to generate response 
- Target: < 3 seconds 

**10. System Reliability**
- Uptime / error rate 
- Target: ≥ 99% uptime

In [12]:
# Import all important libraries
import os
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import json
from urllib.parse import urljoin
import requests
from langchain.chat_models import init_chat_model
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import PDFMinerLoader
from langchain_google_genai import GoogleGenerativeAI
from google import genai
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from dotenv import load_dotenv

load_dotenv()

gemini_api_key = os.getenv("GEMINI_API_KEY")
openai_api_key = os.getenv("OPENAI_API_KEY")
hugging_face_token = os.getenv("HUGGINGFACE_TOKEN")

#### Load Documents

In [2]:
# Scrape Disease Fact Sheets from WHO website
BASE_URL = "https://www.who.int/"
URL = "https://www.who.int/news-room/fact-sheets"

# get response from the URL and parse it using BeautifulSoup
response = requests.get(URL)
soup = BeautifulSoup(response.text,'html.parser')
links = []

# # Extracting all the links of the disease fact sheets
for a in soup.find_all('a', href = True):
    href = a['href']
    if "/news-room/fact-sheets/detail/" in href:
        full_url = urljoin(BASE_URL, href)
        title = a.text.strip()
        links.append((title, full_url))

In [4]:
# Scrape the content of each disease fact sheet 
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

def scrape_content(url):
    response = requests.get(url, headers = headers, timeout=10)
    soup = BeautifulSoup(response.text, 'html.parser')

    # Extract title
    title = soup.find('h1').text.strip() if soup.find('h1') else 'No title found'
    
    # Scrape the content of the page
    content = { }
    content_div = soup.find('article', class_= 'sf-detail-body-wrapper')

    # print(content_div.prettify())
    if content_div:
        # current_heading = None
        required_sections = [
                    'Overview',
                    'Signs and symptoms',
                    'Causes',
                    'Treatment and prevention',
                    'Self-care',
                    'WHO response'
                ]
        current_heading = None
        for tag in content_div.find_all(['h2', 'p','li']):
            # Content headings
            if tag.name == 'h2':
                heading = tag.get_text(strip=True)
                if heading in required_sections:
                    current_heading = heading
                    content[current_heading] = []
                else:
                    current_heading = None
            # Content paragraphs
            elif tag.name == 'p':
                text = tag.get_text(" ",strip=True)
                if text and current_heading:
                    content[current_heading].append(text)
            # Content list items
            elif tag.name == 'li':
                text = tag.get_text(" ",strip=True)
                if text and current_heading:
                    content[current_heading].append(f" - {text}")

    data = {
        "title": title,
        "content": content
    }

    return data

scraped_data = []
for name, link in links:
    data = scrape_content(link)
    scraped_data.append(data)

#### Save Scraped Data in A CSV

In [6]:
# Save the scraped content in a JSON file
with open('../datasets/disease_fact_sheets.json', 'w', encoding='utf-8') as f:
    json.dump(scraped_data, f, indent=4, ensure_ascii=False)

### Load PDF Documents and Excel Documents

In [2]:
medquad_df = pd.read_csv('../datasets/medquad.csv')

medquad_df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

#### Convert MedQuad CSV Data to Documents

In [3]:

medquad_docs = []

for index, row in medquad_df.iterrows():
    text = f"""
            question: {row['question']}

        
            answer:  {row['answer']}
    """
    medquad_docs.append(
        Document(
            page_content=text,
            metadata = {
                'source' : row['source'],
                'focus_area': row['focus_area'],
                'type': 'qa_dataset'
            }

            
        )
    )

print(medquad_docs[0])

page_content='
            question: What is (are) Glaucoma ?


            answer:  Glaucoma is a group of diseases that can damage the eye's optic nerve and result in vision loss and blindness. While glaucoma can strike anyone, the risk is much greater for people over 60. How Glaucoma Develops  There are several different types of glaucoma. Most of these involve the drainage system within the eye. At the front of the eye there is a small space called the anterior chamber. A clear fluid flows through this chamber and bathes and nourishes the nearby tissues. (Watch the video to learn more about glaucoma. To enlarge the video, click the brackets in the lower right-hand corner. To reduce the video, press the Escape (Esc) button on your keyboard.) In glaucoma, for still unknown reasons, the fluid drains too slowly out of the eye. As the fluid builds up, the pressure inside the eye rises. Unless this pressure is controlled, it may cause damage to the optic nerve and other parts of the eye and result in loss of vision. Open-angle Glaucoma The most common type of glaucoma is called open-angle glaucoma. In the normal eye, the clear fluid leaves the anterior chamber at the open angle where the cornea and iris meet. When fluid reaches the angle, it flows through a spongy meshwork, like a drain, and leaves the eye. Sometimes, when the fluid reaches the angle, it passes too slowly through the meshwork drain, causing the pressure inside the eye to build. If the pressure damages the optic nerve, open-angle glaucoma -- and vision loss -- may result. There is no cure for glaucoma. Vision lost from the disease cannot be restored. However, there are treatments that may save remaining vision. That is why early diagnosis is important.  See this graphic for a quick overview of glaucoma,  including how many people it affects, whos at risk, what to do if you have it, and how to learn more.  See a glossary of glaucoma terms.
    ' metadata={'source': 'NIHSeniorHealth', 'focus_area': 'Glaucoma', 'type': 'qa_dataset'}

In [4]:
disease_and_symptoms_df = pd.read_csv('../datasets/Diseases_and_Symptoms_dataset.csv')
disease_and_symptoms_df.head()

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,sneezing,leg weakness,hysterical behavior,arm lump or mass,bleeding gums,pain in gums,diaper rash,hesitancy,back stiffness or tightness,low urine output
0,panic disorder,1,0,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,panic disorder,0,0,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,panic disorder,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,panic disorder,1,0,0,1,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,panic disorder,1,1,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
symptoms_docs = []
symptom_columns = disease_and_symptoms_df[1:] #skip disease columns
for index, row in disease_and_symptoms_df.iterrows():
    disease_name = row['diseases']
    
    symptoms = [ ]
    for symptom in symptom_columns:
        if row[symptom] == 1:
            symptoms.append(symptom)

    text = f"""
        Disease: {disease_name}

    Symptoms:
            {
                ', '.join(symptoms)
            }
            """

    symptoms_docs.append(
            Document (
            page_content = text,
            metadata={
                'disease_name':disease_name,
                'type':'symptoms_dataset'
            }
            )
        )

# print(symptoms_docs[0].page_content)

In [6]:
# Load the Ghana Health Service PDF document
ghs_pdf = PDFMinerLoader('../datasets/GHANA-STG-2017-1.pdf')
ghs_data = ghs_pdf.load()
ghs_data

[Document(metadata={'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign CC 2017 (Windows)', 'creationdate': '2017-08-23T12:37:18+01:00', 'moddate': '2020-07-09T14:43:23+00:00', 'trapped': 'False', 'total_pages': 708, 'source': '../datasets/GHANA-STG-2017-1.pdf'}, page_content='Republic of Ghana\n\nMinistry of Health \nGhana National Drugs Programme \n(GNDP)\n\nStandard Treatment Guidelines\n\nMinistry of Health\nSeventh Edition (7th), 2017\n\ni\n\x0c© 2017 Ministry of Health (GNDP) Ghana\nAll rights reserved. No part of this publication may be reproduced, stored \nin  any  retrieval  system,  or  transmitted  in  any  form  or  by  any  means, \nelectronic,  mechanical,  photocopying,  recording  and/or  otherwise, \nwithout prior written permission of the Ministry of Health.\n\nEssential Drugs List & National Formulary with Therapeutic Guidelines, \n1st Edition, 1988\nEssential Drugs List & National Formulary with Therapeutic Guidelines, \n2nd Edition, 1993\nEssential Drugs List & National Formulary with Therapeutic Guidelines, \n3rd Edition, 1996\nStandard Treatment Guidelines, 4th Edition, 2000\nStandard Treatment Guidelines, 5th Edition, 2004\nStandard Treatment Guidelines, 6th Edition, 2010\nStandard Treatment Guidelines, 7th Edition, 2017\n\nISBN 978-9988-2-5787-3\n\nFor all enquiries write to the publishers:\nGhana National Drugs Programme (GNDP) \nMinistry of Health\nP. O. Box MB-582, Accra, Ghana, West Africa \nTel: +233 (0) 30 2661 670/1\nFax: +233 (0) 30 2664 309 \nE-mail: gndp@ghndp.org\nWebsite: www.ghndp.org\n\nLegal Disclaimer\nCare has been taken to confirm the accuracy of the information presented \nand  to  describe  generally  accepted  practices.  However,  the  authors, \neditors  and  publishers  are  not  responsible  for  errors  and  omissions  or \nany consequences from application of the information in this booklet and \nmake no warranty, expressed or implied, with respect to the content of \nthe publication.\n\nPrinted by:\nYamens Press Limited, P. O. Box AF 274, Accra \nTel: 0302-223 222\nE-mail: yamenspresslimited@gmail.com\n\nCover Design:\nQ-elements Limited, Accra\nTel:  0302-719432, 0268-080618\nE-mail: creative@q-elementsghana.com\n\nii\n\nStandard Treatment Guidelines, 7th Edition, 2017\n\x0cTable of Contents\n\nPreface  ..................................................................................................... xii\nAcknowledgement ................................................................................... xiii\nIntroduction ��������������������������������������������������������������������������������������������������� 1\nHow to use this book ................................................................................. 2\nPrescribing for NHIS reimbursement ......................................................... 3\nNotes on cost-effectiveness ....................................................................... 3\nReferral ...................................................................................................... 4\nAbbreviations ............................................................................................ 4\nPrescription writing ................................................................................... 5\nDosing and medication based on Age and body weight in children .......... 7\nPharmacovigilance and Adverse Drug Event Reporting  ............................ 7\nImportant contacts  ................................................................................... 8\nChapter 1.  Disorders of the Gastrointestinal Tract ��������������������������������� 11\n1.  Diarrhoea ......................................................................................... 11\n2.  Rotavirus Disease and Diarrhoea ..................................................... 18\n3.  Constipation   ................................................................................... 19\n4.  Peptic Ulcer Disease ......................................................................... 22\n5.  Gastro-oesophageal Reflux Disease ................................................. 25\n6.  Pain Originating from the Oesophagus ............................................ 28\n7.  Haemorrhoids .................................................................................. 29\nChapter 2.  Disorders of the Liver  �������������������������������������������������������������� 33\n8.  Amoebic Liver Access ....................................................................... 33\n9. \nJaundice  .......................................................................................... 35\n10.  Acute Hepatitis ................................................................................. 37\n11.  Chronic Hepatitis .............................................................................. 38\n12.  Hepatic Encephalopathy .................................................................. 42\n13.  Ascites .............................................................................................. 46\n14.  Vomiting   ......................................................................................... 48\n15.  Hepatocellular Carcinoma ................................................................ 53\n16.  Drugs and the Liver .......................................................................... 55\nChapter 3.  Nutritional Disorders  �������������������������������������������������������������� 58\n17.  Malnutrition  .................................................................................... 58\nChapter 4.  Haematological Disorders  ������������������������������������������������������� 62\n17.  Anaemia ........................................................................................... 62\n18.  Bleeding Disorders ........................................................................... 65\n19.  Sickle Cell Disease ............................................................................ 69\n20.  Plasma Cell Myeloma ....................................................................... 73\n21.  Leukaemia ........................................................................................ 75\n22.  Malignant Lymphoma ...................................................................... 77\nImmunisable Diseases ���������������������������������������������������������������� 80\n\nChapter 5. \n\niii\n\x0c23.  Immunisation  .................................................................................. 80\n24.  Measles ............................................................................................ 82\n25.  Pertussis  .......................................................................................... 84\n26.  Tetanus ............................................................................................. 86\n27.  Poliomyelitis ..................................................................................... 89\n28.  Diphtheria ........................................................................................ 90\n29.  Yellow Fever ..................................................................................... 92\n30.\t Haemophilus\tInfluenzae type b Disease ........................................... 94\n31.  Pneumococcal Disease ..................................................................... 95\n32.  Hepatitis ........................................................................................... 96\n33.  Rotavirus Disease ............................................................................. 96\nChapter 6.  Problems of the Newborn (Neonate)  ��������������������������������������� 97\n34.  Sick newborn  ................................................................................... 97\n35.  Neonatal Hypoglycaemia   ............................................................. 100\n36.  Neonatal Jaundice  ......................................................................... 101\n37.  Birth Injuries   ................................................................................. 104\n38.  Neonatal conjunctivitis   ................................................................. 106\n39.  Retinoblastoma  ............................................................................. 108\n40.  Wilms Tumour  ............................................................................... 110\nChapter 7.  Disorders of the Cardiovascular System ��������������������������������113\n41.  Chest Pain....................................................................................... 113\n42.  Ischaemic Heart Disease   .............................................................. 115\n43.  Dyspnoea ....................................................................................... 121\n44.  Deep Vein Thrombosis (DVT) ......................................................... 123\n45.  Pulmonary Embolism ..................................................................... 127\n46.  Stroke ............................................................................................. 129\n47.  Heart Failure................................................................................... 134\n48.  Congenital Heart Disease ............................................................... 140\n49.  Hypercyanotic attack ...................................................................... 143\n50.  Pericarditis ..................................................................................... 145\n51.  Hypertension  ................................................................................. 146\n52.  Hypertension in children and adolescents  .................................... 151\n53.  Hypertension in Pregnancy  ........................................................... 154\n54.  Hypertensive Emergencies ............................................................. 154\n55.  Arrhythmias ................................................................................... 156\n56.  Acute Rheumatic Fever .................................................................. 161\n57.  Dizziness and Blackouts.................................................................. 164\nChapter 8.  Disorders of the Respiratory System ���������������������������������������167\n58.  Common Cold ................................................................................ 167\n59.  Pneumonia ..................................................................................... 169\n60.  Bronchial Asthma ........................................................................... 175\n61.  Acute Bronchitis ............................................................................. 180\n62.  Chronic Bronchitis  ......................................................................... 183\n63.  Bronchiectasis ................................................................................ 187\n64.  Lung Abscess .................................................................................. 189\nChapter 9.  Disorders of the Central Nervous System�������������������������������193\n65.  Headache ....................................................................................... 193\n66.  Seizures .......................................................................................... 196\n67.  Epilepsy  ......................................................................................... 200\n68.  The Unconscious Patient ................................................................ 203\nChapter 10.  Psychiatric Disorders ���������������������������������������������������������������207\n69.  Attention Deficit Hyperactivity Disorder (ADHD) ........................... 207\n70.  The Acutely Disturbed Patient ....................................................... 209\n71.  Psychogenic Seizures ...................................................................... 213\n\niv\n\nStandard Treatment Guidelines, 7th Edition, 2017\n\x0c72.  Insomnia ........................................................................................ 214\n73.  Depression ..................................................................................... 216\n74.  Schizophrenia ................................................................................. 220\n75.  Bipolar Disorder ............................................................................. 226\n76.  Alcohol Withdrawal Syndromes   ................................................... 229\n77.  Alcoholic Delirium Tremens  .......................................................... 231\n78.  Anxiety Disorders   ......................................................................... 233\n79.  Substance Use Disorders ................................................................ 239\n80.  Autistic Spectrum Disorder ............................................................ 242\nChapter 11.  Disorders of the Skin ���������������������������������������������������������������245\nBacterial Skin Infections �������������������������������������������������������������245\n81.  Boils   .............................................................................................. 245\n82.  Impetigo  ........................................................................................ 246\n83.    Cellulitis and Erysipelas ................................................................ 249\n84.  Buruli Ulcer .................................................................................... 249\n85.  Yaws  .............................................................................................. 250\nFungal Skin Infections �����������������������������������������������������������������252\n86.  Superficial Fungal Skin Infections ................................................... 252\n87.  Pityriasis Versicolor ........................................................................ 255\nViral Skin Infections  �������������������������������������������������������������������257\n88.  Herpes Simplex Infections  ............................................................. 257\n89.  Herpes Zoster Infections  ............................................................... 259\n90.  Chicken pox  ................................................................................... 261\nNon-Specific Skin Infections  �������������������������������������������������������265\n91.  Large Chronic Ulcers....................................................................... 265\n92.  Pruritus........................................................................................... 267\n93.  Urticaria ......................................................................................... 272\n94.  Reactive Erythema and Bullous Reaction   ..................................... 274\n95.  Acne Vulgaris  ................................................................................. 276\n96.  Eczema  .......................................................................................... 279\n97.  Intertrigo ........................................................................................ 283\nChapter 12.  Endocrine and Metabolic Disorders ���������������������������������������287\n98.  Diabetes Mellitus ........................................................................... 287\n99.  Diabetic Ketoacidosis ..................................................................... 293\n100. Diabetes in Pregnancy  ................................................................... 297\n101. Treatment-Induced Hypoglycaemia ............................................... 298\n102. Dyslipidaemia ................................................................................. 300\n103. Goitre   ........................................................................................... 302\n104. Hypothyroidism   ............................................................................ 303\n105. Hyperthyroidism ............................................................................ 305\n106. Adrenal Insufficiency   .................................................................... 307\n107. Cushing’s Syndrome   ..................................................................... 310\n108. Overweight and Obesity  ................................................................ 311\nChapter 13.  Obstetric Care and Obstetric Disorders ���������������������������������314\n109. Antenatal Care ............................................................................... 314\n110. Hyperemesis Gravidarum ............................................................... 322\n111. Hypertension in Pregnancy ............................................................ 323\n112. Pre-eclampsia ................................................................................. 325\n113. Severe Pre-Eclampsia and Imminent Eclampsia ............................. 326\n114. Eclampsia ....................................................................................... 328\n115. Malaria in Pregnancy  ..................................................................... 331\n116. Anaemia in Pregnancy  ................................................................... 331\n117. Sickle Cell Disease in Pregnancy  .................................................... 334\n118. Diabetes Mellitus in Pregnancy ...................................................... 338\n\nv\n\nTable of Contents\n\x0c119. Cardiac Disease in Pregnancy ......................................................... 341\n120. Jaundice in Pregnancy  ................................................................... 343\n121. Post-Partum Haemorrhage ............................................................ 344\n122. Post-Partum Pyrexia  ...................................................................... 349\n123. Analgesia in Labour ........................................................................ 352\n124. Preterm Labour in Premature Delivery  ......................................... 354\n125. Premature Rupture of the Membranes  ......................................... 356\nChapter 14.  Gynaecological Disorders  ������������������������������������������������������358\n126. Dysmenorrhoea ............................................................................. 358\n127. Abortion ......................................................................................... 359\n128. Abnormal Vaginal Bleeding ............................................................ 371\n129. Abnormal Vaginal Discharge .......................................................... 373\n130. Acute Lower Abdominal Pain ......................................................... 379\n131. Female Infertility ............................................................................ 382\n132. Menopause .................................................................................... 384\n133. Carcinoma of the Cervix  ................................................................ 386\nChapter 15.  Disorders of the Kidney and Genitourinary System ���������������388\n134. Acute Glomerulonephritis .............................................................. 388\n135. Nephrotic Syndrome ...................................................................... 390\n136. Acute Kidney Injury ........................................................................ 392\n137. Chronic Kidney Disease  ................................................................. 396\n138.  Anaemia in Chronic Kidney Disease .............................................. 399\n139. Urinary Tract Infection ................................................................... 401\n140. Medicines and the Kidney .............................................................. 403\n141. Acute Cystitis  ................................................................................. 40

#### Convert WHO from JSON to docs

In [7]:
# load JSON file containing WHO disease fact sheets
who_df= pd.read_json('../datasets/disease_fact_sheets.json')

who_docs = []
for index, row in who_df.iterrows():
    disease_name = row["title"]
    contents = row["content"]
    # Get individual contents from the content
    
    text = f"""
        disease_name : {disease_name}
        overview : {' '.join(contents.get('Overview', []))}
        symptoms : {' '.join(contents.get('Signs and symptoms', []))}
        causes : {' '.join(contents.get('Causes', []))}
        Treatment: {' '.join(contents.get('Treatment and prevention', []))}
        Self-care: {' '.join(contents.get('Self-care', []))}
        WHO response: {' '.join(contents.get('WHO response', []))}

        
    
    """
    
    who_docs.append(
        Document(
            page_content=text,
            metadata={
                'source': 'WHO',
                'type': 'who_disease_fact_sheet'
            }
        )
    )

#### Combine all the Docs

In [8]:
all_docs = ( who_docs + ghs_data + medquad_docs + symptoms_docs)

print(len(all_docs))

112741

### Chunk Documents

In [9]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size = 700,
    chunk_overlap = 150
)

split_docs = splitter.split_documents(all_docs)
print(len(split_docs))

156472

#### Embed Text with HuggingFace Embeddings

In [2]:
model_name = "sentence-transformers/all-MiniLM-L6-v2"
embeddings = HuggingFaceEmbeddings(model_name = model_name, model_kwargs={"device": "cpu"})

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1983.97it/s]

#### Store Embeddings In FAISS

In [11]:
vectorstore = FAISS.from_documents(
    split_docs,
    embeddings
)

In [12]:
# Save embeddings
vectorstore.save_local("medical_rag_embeddings")

#### Load Local Embeddings

In [3]:
# Retrieve embeddings
vectorstore = FAISS.load_local("medical_rag_embeddings", embeddings, allow_dangerous_deserialization=True)

#### Create a Retriever

In [4]:
# Create a retriever from the vectorstore
retriever = vectorstore.as_retriever(
    search_type="mmr",  # Use Maximal Marginal Relevance for retrieval
    search_kwargs = {'k':5,
                     "fetch_k": 20}
)

#### Define GEMINI Model

In [7]:
llm = GoogleGenerativeAI(
    model= "gemini-2.5-flash",
    temperature=0,
    api_key = gemini_api_key
)

#### Create the Prompt

In [10]:
# create prompt template for the RAG model
prompt = PromptTemplate.from_template("""
You are Smart Pocket Doctor.

Use ONLY the provided context to answer.

If the answer is not in the context, say:
"I could not find enough information in the medical database. Kindly consult a healthcare professional for accurate guidance."

Context:
{context}

Question:
{question}

Answer:
""")

### Build the RAG Chain

In [13]:
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = (
    {
        "context": retriever | format_docs,
        "question": RunnablePassthrough(),

    }
    |prompt
    |llm
    |StrOutputParser()
)

In [20]:
# Ask a question to the RAG model
query = "How can I treat malaria?"
response = rag_chain.invoke(query)
print(response)
docs = retriever.invoke(query)
for doc in docs:
    print(doc.metadata)

Malaria can be treated with medicines.

For severe malaria, parenteral antimalarials are recommended for a minimum of 24 hours, followed by oral medication once the patient can tolerate it. Recommended follow-on treatments include Artemisinin Combination Therapy (ACTs) and Quinine + clindamycin.

For uncomplicated malaria, Artemisinin Combination Therapy (ACT) is currently recommended to prevent the development of drug resistance. An example of an ACT regimen provided is Artesunate + Amodiaquine co-blistered formulation.
{'source': 'WHO', 'type': 'who_disease_fact_sheet'}
{'source': 'GARD', 'focus_area': 'Zika virus infection', 'type': 'qa_dataset'}
{'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign CC 2017 (Windows)', 'creationdate': '2017-08-23T12:37:18+01:00', 'moddate': '2020-07-09T14:43:23+00:00', 'trapped': 'False', 'total_pages': 708, 'source': '../datasets/GHANA-STG-2017-1.pdf'}
{'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign CC 2017 (Windows)', 'creationdate': '2017-08-23T12:37:18+01:00', 'moddate': '2020-07-09T14:43:23+00:00', 'trapped': 'False', 'total_pages': 708, 'source': '../datasets/GHANA-STG-2017-1.pdf'}
{'producer': 'Adobe PDF Library 15.0', 'creator': 'Adobe InDesign CC 2017 (Windows)', 'creationdate': '2017-08-23T12:37:18+01:00', 'moddate': '2020-07-09T14:43:23+00:00', 'trapped': 'False', 'total_pages': 708, 'source': '../datasets/GHANA-STG-2017-1.pdf'}

In [5]:
# Create LLM client
client = genai.Client(api_key=gemini_api_key)
# Define the model name
model_name = "gemini-2.5-flash"
# Create a class for the Gemini model
class GEMINI_MODEL:
    # Initialize the class with the client and model name
    def __init__(self, client, model_name):
        self.client = client
        self.model_name = model_name
# Define a method to generate content using the Gemini model
    def generate_content(self, contents):
        response = self.client.models.generate_content(
            model = self.model_name,
            contents = contents
        )
        return response

model = GEMINI_MODEL(client, model_name)

#### Create Embeddings